#!/usr/bin/env python3
"""
Script to setup and test GPS module on Raspberry Pi.
Tests GPS connectivity and location acquisition.
"""

import sys
import time
import logging
from pathlib import Path

# Add modules to path
sys.path.insert(0, str(Path(__file__).parent.parent))

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def check_gpsd_service():
    """Check if GPSD service is running."""
    try:
        import subprocess
        result = subprocess.run(['systemctl', 'is-active', 'gpsd'],
                              capture_output=True, text=True)
        if result.returncode == 0 and result.stdout.strip() == 'active':
            logger.info("GPSD service is active")
            return True
        else:
            logger.warning("GPSD service is not active")
            return False
    except Exception as e:
        logger.error(f"Error checking GPSD service: {e}")
        return False

def test_gps_connection():
    """Test GPS connection using gpsd."""
    try:
        import gpsd
        logger.info("Connecting to GPSD...")

        # Connect to GPSD
        gpsd.connect()

        logger.info("Waiting for GPS fix...")

        # Try to get GPS data
        timeout = 30  # 30 seconds timeout
        start_time = time.time()

        while time.time() - start_time < timeout:
            try:
                packet = gpsd.get_current()

                if packet.mode >= 2:  # 2D or 3D fix
                    logger.info("GPS fix acquired!")
                    logger.info(f"Latitude: {packet.lat}")
                    logger.info(f"Longitude: {packet.lon}")
                    logger.info(f"Altitude: {packet.alt}")
                    logger.info(f"Satellites: {packet.sats}")
                    logger.info(f"Mode: {packet.mode}")
                    return True
                else:
                    logger.info(f"GPS mode: {packet.mode} (waiting for fix...)")

            except Exception as e:
                logger.warning(f"Error reading GPS data: {e}")

            time.sleep(1)

        logger.error("Timeout: No GPS fix acquired within 30 seconds")
        return False

    except ImportError:
        logger.error("gpsd-python package not installed. Install with: pip install gpsd-py3")
        return False
    except Exception as e:
        logger.error(f"GPS test failed: {e}")
        return False

def test_serial_connection():
    """Test direct serial connection to GPS device."""
    try:
        import serial
        device = "/dev/ttyS0"  # Default GPS device

        logger.info(f"Testing serial connection to {device}")

        # Try to open serial port
        ser = serial.Serial(device, baudrate=9600, timeout=1)

        if ser.is_open:
            logger.info("Serial port opened successfully")

            # Read some data
            start_time = time.time()
            data_received = False

            while time.time() - start_time < 10:  # 10 seconds
                if ser.in_waiting > 0:
                    data = ser.readline().decode('utf-8', errors='ignore').strip()
                    if data:
                        logger.info(f"GPS data: {data}")
                        data_received = True
                        break
                time.sleep(0.1)

            ser.close()

            if data_received:
                logger.info("Serial GPS connection test successful")
                return True
            else:
                logger.warning("Serial port opened but no GPS data received")
                return False
        else:
            logger.error("Could not open serial port")
            return False

    except ImportError:
        logger.error("pyserial package not installed. Install with: pip install pyserial")
        return False
    except Exception as e:
        logger.error(f"Serial test failed: {e}")
        return False

def configure_gpsd():
    """Configure GPSD service."""
    try:
        import subprocess

        logger.info("Configuring GPSD service...")

        # Check current configuration
        config_path = "/etc/default/gpsd"
        backup_path = "/etc/default/gpsd.backup"

        # Create backup if it doesn't exist
        if not Path(backup_path).exists():
            subprocess.run(['sudo', 'cp', config_path, backup_path], check=True)
            logger.info("GPSD configuration backed up")

        # Update configuration
        config_content = '''# Default settings for gpsd.
# Please do not edit this file directly - use `dpkg-reconfigure gpsd' to change the options.

START_DAEMON="true"
GPSD_OPTIONS="-n"
DEVICES="/dev/ttyS0"
USBAUTO="true"
SERIALPORT="/dev/ttyS0"
SPEED="9600"
'''

        # Write new configuration
        with open('/tmp/gpsd_config', 'w') as f:
            f.write(config_content)

        subprocess.run(['sudo', 'mv', '/tmp/gpsd_config', config_path], check=True)
        subprocess.run(['sudo', 'chown', 'root:root', config_path], check=True)
        subprocess.run(['sudo', 'chmod', '644', config_path], check=True)

        logger.info("GPSD configuration updated")

        # Restart service
        subprocess.run(['sudo', 'systemctl', 'restart', 'gpsd'], check=True)
        subprocess.run(['sudo', 'systemctl', 'enable', 'gpsd'], check=True)

        logger.info("GPSD service restarted")
        return True

    except Exception as e:
        logger.error(f"Failed to configure GPSD: {e}")
        return False

def main():
    """Main GPS setup function."""
    logger.info("GPS Setup and Testing Script")
    logger.info("=" * 40)

    # Check if running on Raspberry Pi
    try:
        with open('/proc/device-tree/model', 'r') as f:
            model = f.read().strip()
            if 'Raspberry Pi' in model:
                logger.info(f"Running on: {model}")
            else:
                logger.warning("Not running on Raspberry Pi - GPS functionality may not work")
    except:
        logger.warning("Could not detect Raspberry Pi model")

    # Step 1: Configure GPSD
    logger.info("\n--- Step 1: Configuring GPSD ---")
    if not configure_gpsd():
        logger.error("GPSD configuration failed")
        return False

    # Step 2: Check GPSD service
    logger.info("\n--- Step 2: Checking GPSD Service ---")
    if not check_gpsd_service():
        logger.error("GPSD service check failed")
        return False

    # Step 3: Test serial connection
    logger.info("\n--- Step 3: Testing Serial Connection ---")
    serial_ok = test_serial_connection()

    # Step 4: Test GPS connection
    logger.info("\n--- Step 4: Testing GPS Connection ---")
    gps_ok = test_gps_connection()

    # Summary
    logger.info("\n--- Test Results ---")
    logger.info(f"Serial connection: {'✓ PASS' if serial_ok else '✗ FAIL'}")
    logger.info(f"GPS fix: {'✓ PASS' if gps_ok else '✗ FAIL'}")

    if gps_ok:
        logger.info("\n🎉 GPS setup completed successfully!")
        logger.info("The GPS module is ready for use.")
        return True
    else:
        logger.error("\n❌ GPS setup failed.")
        logger.info("Troubleshooting tips:")
        logger.info("1. Check GPS module wiring and power")
        logger.info("2. Ensure GPS has clear view of sky")
        logger.info("3. Try different serial device (/dev/ttyAMA0, /dev/ttyUSB0)")
        logger.info("4. Check GPS module baud rate settings")
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
